// Banques pédagogiques et réglages du jeu Chute des mots.
// Modifier ce fichier suffit pour adapter les contenus en classe.

const TENSES = {
  present: {
    label: "présent",
    color: "#0f6f68",
    hint: "formes fréquentes : suis, ai, vais, fais",
    errorHint: "forme du présent de l'indicatif",
    errorLabel: "c'était du présent",
  },
  imparfait: {
    label: "imparfait",
    color: "#0f8b8d",
    hint: "-ais, -ait, -ions, -iez, -aient",
    errorHint: "terminaisons en -ais, -ait, -ions...",
    errorLabel: "c'était de l'imparfait",
  },
  futur: {
    label: "futur",
    color: "#2867c8",
    hint: "-rai, -ras, -ra, -rons, -rez, -ront",
    errorHint: "base du futur + terminaison",
    errorLabel: "c'était du futur",
  },
  passe_simple: {
    label: "passé simple",
    color: "#7557b8",
    hint: "-ai, -as, -a, -âmes, -âtes, -èrent",
    errorHint: "formes brèves ou littéraires",
    errorLabel: "c'était du passé simple",
  },
  conditionnel_present: {
    label: "conditionnel présent",
    color: "#c95f36",
    hint: "-rais, -rait, -rions, -riez, -raient",
    errorHint: "base du futur + terminaisons de l'imparfait",
    errorLabel: "c'était du conditionnel présent",
  },
  passe_compose: {
    label: "passé composé",
    color: "#1f9d68",
    hint: "auxiliaire + participe passé",
    errorHint: "auxiliaire + participe passé",
    errorLabel: "c'était du passé composé",
  },
};

const TENSE_ORDER = ["present", "passe_compose", "imparfait", "futur", "conditionnel_present", "passe_simple"];
const INITIAL_TENSES = ["present", "passe_compose", "imparfait"];
const DEFAULT_CONTENT_MODE = "tenses";
const CONTENT_MODE_ORDER = ["tenses", "grammar", "lexical", "tools"];

const CHUTE_DES_MOTS_CONTRACT = {
  gameId: "chute-des-mots",
  version: 1,
  completeEventName: "chuteDesMots:complete",
  completeMessageType: "chute-des-mots:complete",
};

// Contrat d'intégration pour lancer Chute des mots depuis un autre jeu.
// Mission ISPA peut surcharger seulement les champs nécessaires via window.ChuteDesMots.start(config).
const DEFAULT_GAME_CONFIG = {
  contentMode: DEFAULT_CONTENT_MODE,
  cefrLevel: "A2",
  playMode: "game",
  wordsPerGame: 30,
  missionId: null,
  successCriteria: {
    minScore: null,
    minCorrect: null,
    minAccuracy: null,
    allowColumnDeath: true,
  },
  integrationMode: false,
  messageTargetOrigin: "*",
};

// Réglages faciles à modifier pour ajuster la durée, le toucher, l'audio et les sensations.
const GAME_RULES = {
  enableProgressiveBucketUnlocks: true,
  wordsPerGame: DEFAULT_GAME_CONFIG.wordsPerGame,
  spawnY: -168,
  spawnDelayMs: 520,
  horizontalEase: 24,
  downAccelerationFactor: 2.35,
  maxErrorBricksPerLane: 4,
  errorBrickHeight: 38,
  correctBaseScore: 10,
  errorPenalty: 5,
  streakBonuses: {
    3: 5,
    5: 10,
    10: 25,
  },
  feedbackDurationMs: 740,
  soundDefaultOn: true,
  musicDefaultOn: true,
  musicVolume: 0.018,
  touchSwipeThreshold: 42,
  touchSwipeDominance: 1.2,
  touchSwipeCooldownMs: 150,
};

// Les niveaux CECRL filtrent surtout le contenu. La vitesse ne bouge que légèrement.
const CEFR_LEVELS = {
  A2: {
    label: "A2",
    baseSpeed: 88,
    speedIncrease: 2,
    maxSpeed: 166,
    contentLevels: ["easy"],
  },
  B1: {
    label: "B1",
    baseSpeed: 112,
    speedIncrease: 3,
    maxSpeed: 216,
    contentLevels: ["easy", "medium"],
  },
  B2: {
    label: "B2",
    baseSpeed: 136,
    speedIncrease: 4.1,
    maxSpeed: 268,
    contentLevels: ["easy", "medium", "hard"],
  },
};

// Petite sélection initiale pour tester rapidement la mécanique.
const TEST_FORMS = [
  { text: "je parlais", tense: "imparfait", verb: "parler", person: "je", level: "easy", irregular: false },
  { text: "nous finirons", tense: "futur", verb: "finir", person: "nous", level: "easy", irregular: false },
  { text: "il prit", tense: "passe_simple", verb: "prendre", person: "il", level: "hard", irregular: true },
  { text: "elles travaillaient", tense: "imparfait", verb: "travailler", person: "elles", level: "easy", irregular: false },
  { text: "tu iras", tense: "futur", verb: "aller", person: "tu", level: "easy", irregular: true },
  { text: "nous vîmes", tense: "passe_simple", verb: "voir", person: "nous", level: "hard", irregular: true },
  { text: "vous aviez", tense: "imparfait", verb: "avoir", person: "vous", level: "easy", irregular: true },
  { text: "ils comprendront", tense: "futur", verb: "comprendre", person: "ils", level: "medium", irregular: true },
  { text: "elle choisit", tense: "passe_simple", verb: "choisir", person: "elle", level: "hard", irregular: false },
  { text: "je parlerais", tense: "conditionnel_present", verb: "parler", person: "je", level: "medium", irregular: false },
  { text: "nous irions", tense: "conditionnel_present", verb: "aller", person: "nous", level: "medium", irregular: true },
  { text: "elle aurait", tense: "conditionnel_present", verb: "avoir", person: "elle", level: "medium", irregular: true },
  { text: "ils feraient", tense: "conditionnel_present", verb: "faire", person: "ils", level: "medium", irregular: true },
  { text: "j'ai parlé", tense: "passe_compose", verb: "parler", person: "je", level: "easy", irregular: false },
  { text: "tu es allé", tense: "passe_compose", verb: "aller", person: "tu", level: "easy", irregular: true },
  { text: "nous avons vu", tense: "passe_compose", verb: "voir", person: "nous", level: "medium", irregular: true },
  { text: "elles ont compris", tense: "passe_compose", verb: "comprendre", person: "elles", level: "medium", irregular: true },
];

// Liste pédagogique principale. Pour ajouter des verbes, copier un objet et modifier
// text, tense, verb, person. Pour ajouter un temps, compléter TENSES et TENSE_ORDER.
const GAME_FORMS = [
  { text: "je suis", tense: "present", verb: "être", person: "je", level: "easy", irregular: true },
  { text: "tu as", tense: "present", verb: "avoir", person: "tu", level: "easy", irregular: true },
  { text: "il va", tense: "present", verb: "aller", person: "il", level: "easy", irregular: true },
  { text: "nous faisons", tense: "present", verb: "faire", person: "nous", level: "easy", irregular: true },
  { text: "elles viennent", tense: "present", verb: "venir", person: "elles", level: "easy", irregular: true },
  { text: "je prends", tense: "present", verb: "prendre", person: "je", level: "easy", irregular: true },
  { text: "tu peux", tense: "present", verb: "pouvoir", person: "tu", level: "easy", irregular: true },
  { text: "elle veut", tense: "present", verb: "vouloir", person: "elle", level: "easy", irregular: true },
  { text: "nous devons", tense: "present", verb: "devoir", person: "nous", level: "easy", irregular: true },
  { text: "vous parlez", tense: "present", verb: "parler", person: "vous", level: "easy", irregular: false },
  { text: "j'aime", tense: "present", verb: "aimer", person: "je", level: "easy", irregular: false },
  { text: "ils habitent", tense: "present", verb: "habiter", person: "ils", level: "easy", irregular: false },
  { text: "elle travaille", tense: "present", verb: "travailler", person: "elle", level: "easy", irregular: false },
  { text: "nous choisissons", tense: "present", verb: "choisir", person: "nous", level: "medium", irregular: false },
  { text: "vous obtenez", tense: "present", verb: "obtenir", person: "vous", level: "medium", irregular: true },
  { text: "ils supposent", tense: "present", verb: "supposer", person: "ils", level: "hard", irregular: false },
  { text: "j'étais", tense: "imparfait", verb: "être", person: "je", level: "easy", irregular: true },
  { text: "tu étais", tense: "imparfait", verb: "être", person: "tu", level: "easy", irregular: true },
  { text: "nous étions", tense: "imparfait", verb: "être", person: "nous", level: "easy", irregular: true },
  { text: "elles étaient", tense: "imparfait", verb: "être", person: "elles", level: "easy", irregular: true },
  { text: "j'avais", tense: "imparfait", verb: "avoir", person: "je", level: "easy", irregular: true },
  { text: "il avait", tense: "imparfait", verb: "avoir", person: "il", level: "easy", irregular: true },
  { text: "vous aviez", tense: "imparfait", verb: "avoir", person: "vous", level: "easy", irregular: true },
  { text: "nous allions", tense: "imparfait", verb: "aller", person: "nous", level: "easy", irregular: true },
  { text: "ils allaient", tense: "imparfait", verb: "aller", person: "ils", level: "easy", irregular: true },
  { text: "je faisais", tense: "imparfait", verb: "faire", person: "je", level: "easy", irregular: true },
  { text: "vous faisiez", tense: "imparfait", verb: "faire", person: "vous", level: "easy", irregular: true },
  { text: "elle venait", tense: "imparfait", verb: "venir", person: "elle", level: "easy", irregular: true },
  { text: "nous venions", tense: "imparfait", verb: "venir", person: "nous", level: "medium", irregular: true },
  { text: "tu prenais", tense: "imparfait", verb: "prendre", person: "tu", level: "easy", irregular: true },
  { text: "ils prenaient", tense: "imparfait", verb: "prendre", person: "ils", level: "easy", irregular: true },
  { text: "je voyais", tense: "imparfait", verb: "voir", person: "je", level: "easy", irregular: true },
  { text: "nous voyions", tense: "imparfait", verb: "voir", person: "nous", level: "medium", irregular: true },
  { text: "il pouvait", tense: "imparfait", verb: "pouvoir", person: "il", level: "easy", irregular: true },
  { text: "vous pouviez", tense: "imparfait", verb: "pouvoir", person: "vous", level: "easy", irregular: true },
  { text: "je voulais", tense: "imparfait", verb: "vouloir", person: "je", level: "easy", irregular: true },
  { text: "elles voulaient", tense: "imparfait", verb: "vouloir", person: "elles", level: "easy", irregular: true },
  { text: "tu devais", tense: "imparfait", verb: "devoir", person: "tu", level: "easy", irregular: true },
  { text: "nous devions", tense: "imparfait", verb: "devoir", person: "nous", level: "medium", irregular: true },
  { text: "il disait", tense: "imparfait", verb: "dire", person: "il", level: "easy", irregular: true },
  { text: "vous disiez", tense: "imparfait", verb: "dire", person: "vous", level: "easy", irregular: true },
  { text: "je lisais", tense: "imparfait", verb: "lire", person: "je", level: "easy", irregular: true },
  { text: "elles lisaient", tense: "imparfait", verb: "lire", person: "elles", level: "easy", irregular: true },
  { text: "tu écrivais", tense: "imparfait", verb: "écrire", person: "tu", level: "easy", irregular: true },
  { text: "nous écrivions", tense: "imparfait", verb: "écrire", person: "nous", level: "medium", irregular: true },
  { text: "je mettais", tense: "imparfait", verb: "mettre", person: "je", level: "easy", irregular: true },
  { text: "ils mettaient", tense: "imparfait", verb: "mettre", person: "ils", level: "easy", irregular: true },
  { text: "elle partait", tense: "imparfait", verb: "partir", person: "elle", level: "easy", irregular: true },
  { text: "nous sortions", tense: "imparfait", verb: "sortir", person: "nous", level: "easy", irregular: true },
  { text: "je finissais", tense: "imparfait", verb: "finir", person: "je", level: "easy", irregular: false },
  { text: "vous choisissiez", tense: "imparfait", verb: "choisir", person: "vous", level: "easy", irregular: false },
  { text: "tu parlais", tense: "imparfait", verb: "parler", person: "tu", level: "easy", irregular: false },
  { text: "elle aimait", tense: "imparfait", verb: "aimer", person: "elle", level: "easy", irregular: false },
  { text: "nous habitions", tense: "imparfait", verb: "habiter", person: "nous", level: "easy", irregular: false },
  { text: "ils travaillaient", tense: "imparfait", verb: "travailler", person: "ils", level: "easy", irregular: false },
  { text: "je mangeais", tense: "imparfait", verb: "manger", person: "je", level: "easy", irregular: false },
  { text: "nous commencions", tense: "imparfait", verb: "commencer", person: "nous", level: "medium", irregular: false },
  { text: "tu apprenais", tense: "imparfait", verb: "apprendre", person: "tu", level: "medium", irregular: true },
  { text: "ils comprenaient", tense: "imparfait", verb: "comprendre", person: "ils", level: "medium", irregular: true },
  { text: "je connaissais", tense: "imparfait", verb: "connaître", person: "je", level: "medium", irregular: true },
  { text: "elle buvait", tense: "imparfait", verb: "boire", person: "elle", level: "medium", irregular: true },
  { text: "nous vivions", tense: "imparfait", verb: "vivre", person: "nous", level: "medium", irregular: true },
  { text: "ils attendaient", tense: "imparfait", verb: "attendre", person: "ils", level: "easy", irregular: false },
  { text: "vous vendiez", tense: "imparfait", verb: "vendre", person: "vous", level: "easy", irregular: false },

  { text: "je serai", tense: "futur", verb: "être", person: "je", level: "easy", irregular: true },
  { text: "tu seras", tense: "futur", verb: "être", person: "tu", level: "easy", irregular: true },
  { text: "nous serons", tense: "futur", verb: "être", person: "nous", level: "easy", irregular: true },
  { text: "ils auront", tense: "futur", verb: "avoir", person: "ils", level: "easy", irregular: true },
  { text: "j'aurai", tense: "futur", verb: "avoir", person: "je", level: "easy", irregular: true },
  { text: "vous aurez", tense: "futur", verb: "avoir", person: "vous", level: "easy", irregular: true },
  { text: "j'irai", tense: "futur", verb: "aller", person: "je", level: "easy", irregular: true },
  { text: "tu iras", tense: "futur", verb: "aller", person: "tu", level: "easy", irregular: true },
  { text: "elles iront", tense: "futur", verb: "aller", person: "elles", level: "easy", irregular: true },
  { text: "je ferai", tense: "futur", verb: "faire", person: "je", level: "easy", irregular: true },
  { text: "nous ferons", tense: "futur", verb: "faire", person: "nous", level: "easy", irregular: true },
  { text: "il viendra", tense: "futur", verb: "venir", person: "il", level: "easy", irregular: true },
  { text: "vous viendrez", tense: "futur", verb: "venir", person: "vous", level: "medium", irregular: true },
  { text: "je prendrai", tense: "futur", verb: "prendre", person: "je", level: "easy", irregular: true },
  { text: "elles prendront", tense: "futur", verb: "prendre", person: "elles", level: "easy", irregular: true },
  { text: "tu verras", tense: "futur", verb: "voir", person: "tu", level: "easy", irregular: true },
  { text: "nous verrons", tense: "futur", verb: "voir", person: "nous", level: "medium", irregular: true },
  { text: "je pourrai", tense: "futur", verb: "pouvoir", person: "je", level: "easy", irregular: true },
  { text: "ils pourront", tense: "futur", verb: "pouvoir", person: "ils", level: "easy", irregular: true },
  { text: "tu voudras", tense: "futur", verb: "vouloir", person: "tu", level: "easy", irregular: true },
  { text: "elle voudra", tense: "futur", verb: "vouloir", person: "elle", level: "easy", irregular: true },
  { text: "je devrai", tense: "futur", verb: "devoir", person: "je", level: "easy", irregular: true },
  { text: "nous devrons", tense: "futur", verb: "devoir", person: "nous", level: "medium", irregular: true },
  { text: "il dira", tense: "futur", verb: "dire", person: "il", level: "easy", irregular: true },
  { text: "vous direz", tense: "futur", verb: "dire", person: "vous", level: "easy", irregular: true },
  { text: "je lirai", tense: "futur", verb: "lire", person: "je", level: "easy", irregular: true },
  { text: "elles liront", tense: "futur", verb: "lire", person: "elles", level: "easy", irregular: true },
  { text: "tu écriras", tense: "futur", verb: "écrire", person: "tu", level: "easy", irregular: true },
  { text: "nous écrirons", tense: "futur", verb: "écrire", person: "nous", level: "medium", irregular: true },
  { text: "je mettrai", tense: "futur", verb: "mettre", person: "je", level: "easy", irregular: true },
  { text: "ils mettront", tense: "futur", verb: "mettre", person: "ils", level: "easy", irregular: true },
  { text: "elle partira", tense: "futur", verb: "partir", person: "elle", level: "easy", irregular: true },
  { text: "nous sortirons", tense: "futur", verb: "sortir", person: "nous", level: "easy", irregular: true },
  { text: "je finirai", tense: "futur", verb: "finir", person: "je", level: "easy", irregular: false },
  { text: "vous choisirez", tense: "futur", verb: "choisir", person: "vous", level: "easy", irregular: false },
  { text: "tu parleras", tense: "futur", verb: "parler", person: "tu", level: "easy", irregular: false },
  { text: "elle aimera", tense: "futur", verb: "aimer", person: "elle", level: "easy", irregular: false },
  { text: "nous habiterons", tense: "futur", verb: "habiter", person: "nous", level: "easy", irregular: false },
  { text: "ils travailleront", tense: "futur", verb: "travailler", person: "ils", level: "easy", irregular: false },
  { text: "je mangerai", tense: "futur", verb: "manger", person: "je", level: "easy", irregular: false },
  { text: "nous commencerons", tense: "futur", verb: "commencer", person: "nous", level: "medium", irregular: false },
  { text: "tu apprendras", tense: "futur", verb: "apprendre", person: "tu", level: "medium", irregular: true },
  { text: "ils comprendront", tense: "futur", verb: "comprendre", person: "ils", level: "medium", irregular: true },
  { text: "je connaîtrai", tense: "futur", verb: "connaître", person: "je", level: "medium", irregular: true },
  { text: "elle boira", tense: "futur", verb: "boire", person: "elle", level: "medium", irregular: true },
  { text: "nous vivrons", tense: "futur", verb: "vivre", person: "nous", level: "medium", irregular: true },
  { text: "ils attendront", tense: "futur", verb: "attendre", person: "ils", level: "easy", irregular: false },
  { text: "vous vendrez", tense: "futur", verb: "vendre", person: "vous", level: "easy", irregular: false },

  { text: "je fus", tense: "passe_simple", verb: "être", person: "je", level: "hard", irregular: true },
  { text: "il fut", tense: "passe_simple", verb: "être", person: "il", level: "hard", irregular: true },
  { text: "ils furent", tense: "passe_simple", verb: "être", person: "ils", level: "hard", irregular: true },
  { text: "j'eus", tense: "passe_simple", verb: "avoir", person: "je", level: "hard", irregular: true },
  { text: "elle eut", tense: "passe_simple", verb: "avoir", person: "elle", level: "hard", irregular: true },
  { text: "nous eûmes", tense: "passe_simple", verb: "avoir", person: "nous", level: "hard", irregular: true },
  { text: "j'allai", tense: "passe_simple", verb: "aller", person: "je", level: "hard", irregular: true },
  { text: "tu allas", tense: "passe_simple", verb: "aller", person: "tu", level: "hard", irregular: true },
  { text: "ils allèrent", tense: "passe_simple", verb: "aller", person: "ils", level: "hard", irregular: true },
  { text: "je fis", tense: "passe_simple", verb: "faire", person: "je", level: "hard", irregular: true },
  { text: "elle fit", tense: "passe_simple", verb: "faire", person: "elle", level: "hard", irregular: true },
  { text: "vous fîtes", tense: "passe_simple", verb: "faire", person: "vous", level: "hard", irregular: true },
  { text: "il vint", tense: "passe_simple", verb: "venir", person: "il", level: "hard", irregular: true },
  { text: "ils vinrent", tense: "passe_simple", verb: "venir", person: "ils", level: "hard", irregular: true },
  { text: "je pris", tense: "passe_simple", verb: "prendre", person: "je", level: "hard", irregular: true },
  { text: "elle prit", tense: "passe_simple", verb: "prendre", person: "elle", level: "hard", irregular: true },
  { text: "nous prîmes", tense: "passe_simple", verb: "prendre", person: "nous", level: "hard", irregular: true },
  { text: "je vis", tense: "passe_simple", verb: "voir", person: "je", level: "hard", irregular: true },
  { text: "il vit", tense: "passe_simple", verb: "voir", person: "il", level: "hard", irregular: true },
  { text: "nous vîmes", tense: "passe_simple", verb: "voir", person: "nous", level: "hard", irregular: true },
  { text: "je pus", tense: "passe_simple", verb: "pouvoir", person: "je", level: "hard", irregular: true },
  { text: "elles purent", tense: "passe_simple", verb: "pouvoir", person: "elles", level: "hard", irregular: true },
  { text: "tu voulus", tense: "passe_simple", verb: "vouloir", person: "tu", level: "hard", irregular: true },
  { text: "il voulut", tense: "passe_simple", verb: "vouloir", person: "il", level: "hard", irregular: true },
  { text: "je dus", tense: "passe_simple", verb: "devoir", person: "je", level: "hard", irregular: true },
  { text: "nous dûmes", tense: "passe_simple", verb: "devoir", person: "nous", level: "hard", irregular: true },
  { text: "il dit", tense: "passe_simple", verb: "dire", person: "il", level: "hard", irregular: true },
  { text: "ils dirent", tense: "passe_simple", verb: "dire", person: "ils", level: "hard", irregular: true },
  { text: "je lus", tense: "passe_simple", verb: "lire", person: "je", level: "hard", irregular: true },
  { text: "elles lurent", tense: "passe_simple", verb: "lire", person: "elles", level: "hard", irregular: true },
  { text: "tu écrivis", tense: "passe_simple", verb: "écrire", person: "tu", level: "hard", irregular: true },
  { text: "nous écrivîmes", tense: "passe_simple", verb: "écrire", person: "nous", level: "hard", irregular: true },
  { text: "je mis", tense: "passe_simple", verb: "mettre", person: "je", level: "hard", irregular: true },
  { text: "ils mirent", tense: "passe_simple", verb: "mettre", person: "ils", level: "hard", irregular: true },
  { text: "elle partit", tense: "passe_simple", verb: "partir", person: "elle", level: "hard", irregular: true },
  { text: "nous sortîmes", tense: "passe_simple", verb: "sortir", person: "nous", level: "hard", irregular: true },
  { text: "je finis", tense: "passe_simple", verb: "finir", person: "je", level: "hard", irregular: false },
  { text: "elle choisit", tense: "passe_simple", verb: "choisir", person: "elle", level: "hard", irregular: false },
  { text: "je parlai", tense: "passe_simple", verb: "parler", person: "je", level: "hard", irregular: false },
  { text: "tu aimas", tense: "passe_simple", verb: "aimer", person: "tu", level: "hard", irregular: false },
  { text: "nous habitâmes", tense: "passe_simple", verb: "habiter", person: "nous", level: "hard", irregular: false },
  { text: "ils travaillèrent", tense: "passe_simple", verb: "travailler", person: "ils", level: "hard", irregular: false },
  { text: "je mangeai", tense: "passe_simple", verb: "manger", person: "je", level: "hard", irregular: false },
  { text: "nous commençâmes", tense: "passe_simple", verb: "commencer", person: "nous", level: "hard", irregular: false },
  { text: "tu appris", tense: "passe_simple", verb: "apprendre", person: "tu", level: "hard", irregular: true },
  { text: "ils comprirent", tense: "passe_simple", verb: "comprendre", person: "ils", level: "hard", irregular: true },
  { text: "je connus", tense: "passe_simple", verb: "connaître", person: "je", level: "hard", irregular: true },
  { text: "elle but", tense: "passe_simple", verb: "boire", person: "elle", level: "hard", irregular: true },
  { text: "nous vécûmes", tense: "passe_simple", verb: "vivre", person: "nous", level: "hard", irregular: true },
  { text: "ils attendirent", tense: "passe_simple", verb: "attendre", person: "ils", level: "hard", irregular: false },
  { text: "vous vendîtes", tense: "passe_simple", verb: "vendre", person: "vous", level: "hard", irregular: false },

  { text: "je serais", tense: "conditionnel_present", verb: "être", person: "je", level: "medium", irregular: true },
  { text: "tu serais", tense: "conditionnel_present", verb: "être", person: "tu", level: "medium", irregular: true },
  { text: "nous serions", tense: "conditionnel_present", verb: "être", person: "nous", level: "medium", irregular: true },
  { text: "ils auraient", tense: "conditionnel_present", verb: "avoir", person: "ils", level: "medium", irregular: true },
  { text: "j'aurais", tense: "conditionnel_present", verb: "avoir", person: "je", level: "medium", irregular: true },
  { text: "vous auriez", tense: "conditionnel_present", verb: "avoir", person: "vous", level: "medium", irregular: true },
  { text: "j'irais", tense: "conditionnel_present", verb: "aller", person: "je", level: "medium", irregular: true },
  { text: "nous irions", tense: "conditionnel_present", verb: "aller", person: "nous", level: "medium", irregular: true },
  { text: "elles iraient", tense: "conditionnel_present", verb: "aller", person: "elles", level: "medium", irregular: true },
  { text: "je ferais", tense: "conditionnel_present", verb: "faire", person: "je", level: "medium", irregular: true },
  { text: "vous feriez", tense: "conditionnel_present", verb: "faire", person: "vous", level: "medium", irregular: true },
  { text: "il viendrait", tense: "conditionnel_present", verb: "venir", person: "il", level: "medium", irregular: true },
  { text: "elles viendraient", tense: "conditionnel_present", verb: "venir", person: "elles", level: "medium", irregular: true },
  { text: "je prendrais", tense: "conditionnel_present", verb: "prendre", person: "je", level: "medium", irregular: true },
  { text: "nous prendrions", tense: "conditionnel_present", verb: "prendre", person: "nous", level: "medium", irregular: true },
  { text: "tu verrais", tense: "conditionnel_present", verb: "voir", person: "tu", level: "medium", irregular: true },
  { text: "nous verrions", tense: "conditionnel_present", verb: "voir", person: "nous", level: "medium", irregular: true },
  { text: "je pourrais", tense: "conditionnel_present", verb: "pouvoir", person: "je", level: "medium", irregular: true },
  { text: "ils pourraient", tense: "conditionnel_present", verb: "pouvoir", person: "ils", level: "medium", irregular: true },
  { text: "tu voudrais", tense: "conditionnel_present", verb: "vouloir", person: "tu", level: "medium", irregular: true },
  { text: "elle voudrait", tense: "conditionnel_present", verb: "vouloir", person: "elle", level: "medium", irregular: true },
  { text: "je devrais", tense: "conditionnel_present", verb: "devoir", person: "je", level: "medium", irregular: true },
  { text: "nous devrions", tense: "conditionnel_present", verb: "devoir", person: "nous", level: "medium", irregular: true },
  { text: "il dirait", tense: "conditionnel_present", verb: "dire", person: "il", level: "medium", irregular: true },
  { text: "vous diriez", tense: "conditionnel_present", verb: "dire", person: "vous", level: "medium", irregular: true },
  { text: "je lirais", tense: "conditionnel_present", verb: "lire", person: "je", level: "medium", irregular: true },
  { text: "tu écrirais", tense: "conditionnel_present", verb: "écrire", person: "tu", level: "medium", irregular: true },
  { text: "ils mettraient", tense: "conditionnel_present", verb: "mettre", person: "ils", level: "medium", irregular: true },
  { text: "elle partirait", tense: "conditionnel_present", verb: "partir", person: "elle", level: "medium", irregular: true },
  { text: "nous sortirions", tense: "conditionnel_present", verb: "sortir", person: "nous", level: "medium", irregular: true },
  { text: "je finirais", tense: "conditionnel_present", verb: "finir", person: "je", level: "medium", irregular: false },
  { text: "vous choisiriez", tense: "conditionnel_present", verb: "choisir", person: "vous", level: "medium", irregular: false },
  { text: "tu parlerais", tense: "conditionnel_present", verb: "parler", person: "tu", level: "medium", irregular: false },
  { text: "elle aimerait", tense: "conditionnel_present", verb: "aimer", person: "elle", level: "medium", irregular: false },
  { text: "nous habiterions", tense: "conditionnel_present", verb: "habiter", person: "nous", level: "medium", irregular: false },
  { text: "ils travailleraient", tense: "conditionnel_present", verb: "travailler", person: "ils", level: "medium", irregular: false },
  { text: "je mangerais", tense: "conditionnel_present", verb: "manger", person: "je", level: "medium", irregular: false },
  { text: "nous commencerions", tense: "conditionnel_present", verb: "commencer", person: "nous", level: "medium", irregular: false },
  { text: "tu apprendrais", tense: "conditionnel_present", verb: "apprendre", person: "tu", level: "medium", irregular: true },
  { text: "ils comprendraient", tense: "conditionnel_present", verb: "comprendre", person: "ils", level: "medium", irregular: true },
  { text: "je connaîtrais", tense: "conditionnel_present", verb: "connaître", person: "je", level: "medium", irregular: true },
  { text: "elle boirait", tense: "conditionnel_present", verb: "boire", person: "elle", level: "medium", irregular: true },
  { text: "nous vivrions", tense: "conditionnel_present", verb: "vivre", person: "nous", level: "medium", irregular: true },
  { text: "ils attendraient", tense: "conditionnel_present", verb: "attendre", person: "ils", level: "medium", irregular: false },
  { text: "vous vendriez", tense: "conditionnel_present", verb: "vendre", person: "vous", level: "medium", irregular: false },

  { text: "j'ai été", tense: "passe_compose", verb: "être", person: "je", level: "easy", irregular: true },
  { text: "tu as été", tense: "passe_compose", verb: "être", person: "tu", level: "easy", irregular: true },
  { text: "nous avons été", tense: "passe_compose", verb: "être", person: "nous", level: "easy", irregular: true },
  { text: "j'ai eu", tense: "passe_compose", verb: "avoir", person: "je", level: "easy", irregular: true },
  { text: "elle a eu", tense: "passe_compose", verb: "avoir", person: "elle", level: "easy", irregular: true },
  { text: "vous avez eu", tense: "passe_compose", verb: "avoir", person: "vous", level: "easy", irregular: true },
  { text: "je suis allé", tense: "passe_compose", verb: "aller", person: "je", level: "easy", irregular: true },
  { text: "tu es allé", tense: "passe_compose", verb: "aller", person: "tu", level: "easy", irregular: true },
  { text: "elles sont allées", tense: "passe_compose", verb: "aller", person: "elles", level: "easy", irregular: true },
  { text: "j'ai fait", tense: "passe_compose", verb: "faire", person: "je", level: "easy", irregular: true },
  { text: "nous avons fait", tense: "passe_compose", verb: "faire", person: "nous", level: "easy", irregular: true },
  { text: "il est venu", tense: "passe_compose", verb: "venir", person: "il", level: "easy", irregular: true },
  { text: "elles sont venues", tense: "passe_compose", verb: "venir", person: "elles", level: "medium", irregular: true },
  { text: "j'ai pris", tense: "passe_compose", verb: "prendre", person: "je", level: "easy", irregular: true },
  { text: "nous avons pris", tense: "passe_compose", verb: "prendre", person: "nous", level: "medium", irregular: true },
  { text: "tu as vu", tense: "passe_compose", verb: "voir", person: "tu", level: "easy", irregular: true },
  { text: "nous avons vu", tense: "passe_compose", verb: "voir", person: "nous", level: "medium", irregular: true },
  { text: "j'ai pu", tense: "passe_compose", verb: "pouvoir", person: "je", level: "easy", irregular: true },
  { text: "ils ont pu", tense: "passe_compose", verb: "pouvoir", person: "ils", level: "easy", irregular: true },
  { text: "tu as voulu", tense: "passe_compose", verb: "vouloir", person: "tu", level: "easy", irregular: true },
  { text: "elle a voulu", tense: "passe_compose", verb: "vouloir", person: "elle", level: "easy", irregular: true },
  { text: "j'ai dû", tense: "passe_compose", verb: "devoir", person: "je", level: "easy", irregular: true },
  { text: "nous avons dû", tense: "passe_compose", verb: "devoir", person: "nous", level: "medium", irregular: true },
  { text: "il a dit", tense: "passe_compose", verb: "dire", person: "il", level: "easy", irregular: true },
  { text: "vous avez dit", tense: "passe_compose", verb: "dire", person: "vous", level: "easy", irregular: true },
  { text: "j'ai lu", tense: "passe_compose", verb: "lire", person: "je", level: "easy", irregular: true },
  { text: "tu as écrit", tense: "passe_compose", verb: "écrire", person: "tu", level: "medium", irregular: true },
  { text: "ils ont mis", tense: "passe_compose", verb: "mettre", person: "ils", level: "easy", irregular: true },
  { text: "elle est partie", tense: "passe_compose", verb: "partir", person: "elle", level: "easy", irregular: true },
  { text: "nous sommes sortis", tense: "passe_compose", verb: "sortir", person: "nous", level: "easy", irregular: true },
  { text: "j'ai fini", tense: "passe_compose", verb: "finir", person: "je", level: "easy", irregular: false },
  { text: "vous avez choisi", tense: "passe_compose", verb: "choisir", person: "vous", level: "easy", irregular: false },
  { text: "tu as parlé", tense: "passe_compose", verb: "parler", person: "tu", level: "easy", irregular: false },
  { text: "elle a aimé", tense: "passe_compose", verb: "aimer", person: "elle", level: "easy", irregular: false },
  { text: "nous avons habité", tense: "passe_compose", verb: "habiter", person: "nous", level: "easy", irregular: false },
  { text: "ils ont travaillé", tense: "passe_compose", verb: "travailler", person: "ils", level: "easy", irregular: false },
  { text: "j'ai mangé", tense: "passe_compose", verb: "manger", person: "je", level: "easy", irregular: false },
  { text: "nous avons commencé", tense: "passe_compose", verb: "commencer", person: "nous", level: "medium", irregular: false },
  { text: "tu as appris", tense: "passe_compose", verb: "apprendre", person: "tu", level: "medium", irregular: true },
  { text: "ils ont compris", tense: "passe_compose", verb: "comprendre", person: "ils", level: "medium", irregular: true },
  { text: "j'ai connu", tense: "passe_compose", verb: "connaître", person: "je", level: "medium", irregular: true },
  { text: "elle a bu", tense: "passe_compose", verb: "boire", person: "elle", level: "medium", irregular: true },
  { text: "nous avons vécu", tense: "passe_compose", verb: "vivre", person: "nous", level: "medium", irregular: true },
  { text: "ils ont attendu", tense: "passe_compose", verb: "attendre", person: "ils", level: "easy", irregular: false },
  { text: "vous avez vendu", tense: "passe_compose", verb: "vendre", person: "vous", level: "easy", irregular: false },
];

const GRAMMAR_BUCKETS = {
  nom: {
    label: "nom",
    color: "#0f8b8d",
    hint: "personne, lieu, objet ou idée",
    errorHint: "on peut souvent mettre un déterminant devant",
    errorLabel: "c'était un nom",
  },
  verbe: {
    label: "verbe",
    color: "#2867c8",
    hint: "action ou état",
    errorHint: "il se conjugue avec un sujet",
    errorLabel: "c'était un verbe",
  },
  adjectif: {
    label: "adjectif",
    color: "#c95f36",
    hint: "précise un nom",
    errorHint: "il décrit une qualité",
    errorLabel: "c'était un adjectif",
  },
  adverbe: {
    label: "adverbe",
    color: "#1f9d68",
    hint: "précise un verbe ou une phrase",
    errorHint: "il indique souvent comment, où ou quand",
    errorLabel: "c'était un adverbe",
  },
  pronom: {
    label: "pronom",
    color: "#7557b8",
    hint: "remplace un nom ou un groupe nominal",
    errorHint: "il évite de répéter un nom",
    errorLabel: "c'était un pronom",
  },

  determinant: {
    label: "déterminant",
    color: "#8a6d1d",
    hint: "introduit un nom : le, une, des",
    errorHint: "il se place devant un nom",
    errorLabel: "c'était un déterminant",
  },
  preposition: {
    label: "préposition",
    color: "#5d7c2f",
    hint: "relie un mot à un complément",
    errorHint: "elle introduit souvent un lieu, un temps ou un moyen",
    errorLabel: "c'était une préposition",
  },
  conjonction: {
    label: "conjonction",
    color: "#a64f77",
    hint: "relie deux mots, groupes ou propositions",
    errorHint: "elle sert à relier des idées",
    errorLabel: "c'était une conjonction",
  },
  interjection: {
    label: "interjection",
    color: "#8d4f20",
    hint: "exprime une réaction brève",
    errorHint: "c'est un mot exclamatif ou une réaction",
    errorLabel: "c'était une interjection",
  },
};

const GRAMMAR_ORDER = ["nom", "verbe", "adjectif", "adverbe", "pronom", "determinant", "preposition", "conjonction", "interjection"];

const GRAMMAR_ITEMS = [
  { text: "table", answer: "nom", level: "easy", tags: ["objet"], hint: "un objet" },
  { text: "voiture", answer: "nom", level: "easy", tags: ["objet"], hint: "un objet" },
  { text: "étudiant", answer: "nom", level: "easy", tags: ["personne"], hint: "une personne" },
  { text: "livre", answer: "nom", level: "easy", tags: ["objet"], hint: "un objet" },
  { text: "maison", answer: "nom", level: "easy", tags: ["lieu"], hint: "un lieu" },
  { text: "école", answer: "nom", level: "easy", tags: ["lieu"], hint: "un lieu" },
  { text: "jardin", answer: "nom", level: "easy", tags: ["lieu"], hint: "un lieu" },
  { text: "chaise", answer: "nom", level: "easy", tags: ["objet"], hint: "un objet" },
  { text: "fenêtre", answer: "nom", level: "medium", tags: ["objet"], hint: "un objet" },
  { text: "ordinateur", answer: "nom", level: "medium", tags: ["objet"], hint: "un objet" },
  { text: "dormir", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "courir", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "écrire", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "chanter", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "manger", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "parler", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "lire", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "voyager", answer: "verbe", level: "medium", tags: ["infinitif"], hint: "une action" },
  { text: "attendre", answer: "verbe", level: "medium", tags: ["infinitif"], hint: "une action" },
  { text: "choisir", answer: "verbe", level: "medium", tags: ["infinitif"], hint: "une action" },
  { text: "grand", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "utile", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "rapide", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "joli", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "bleu", answer: "adjectif", level: "easy", tags: ["couleur"], hint: "une qualité" },
  { text: "chaud", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "propre", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "difficile", answer: "adjectif", level: "medium", tags: ["qualité"], hint: "une qualité" },
  { text: "simple", answer: "adjectif", level: "medium", tags: ["qualité"], hint: "une qualité" },
  { text: "ancien", answer: "adjectif", level: "medium", tags: ["qualité"], hint: "une qualité" },
  { text: "vite", answer: "adverbe", level: "easy", tags: ["manière"], hint: "comment ?" },
  { text: "souvent", answer: "adverbe", level: "easy", tags: ["fréquence"], hint: "combien de fois ?" },
  { text: "demain", answer: "adverbe", level: "easy", tags: ["temps"], hint: "quand ?" },
  { text: "ici", answer: "adverbe", level: "easy", tags: ["lieu"], hint: "où ?" },
  { text: "dehors", answer: "adverbe", level: "easy", tags: ["lieu"], hint: "où ?" },
  { text: "bientôt", answer: "adverbe", level: "medium", tags: ["temps"], hint: "quand ?" },
  { text: "toujours", answer: "adverbe", level: "medium", tags: ["fréquence"], hint: "combien de fois ?" },
  { text: "lentement", answer: "adverbe", level: "medium", tags: ["manière"], hint: "comment ?" },
  { text: "maintenant", answer: "adverbe", level: "medium", tags: ["temps"], hint: "quand ?" },
  { text: "ailleurs", answer: "adverbe", level: "hard", tags: ["lieu"], hint: "où ?" },
  { text: "elle", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace un nom" },
  { text: "nous", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace un nom" },
  { text: "ceci", answer: "pronom", level: "medium", tags: ["démonstratif"], hint: "remplace une chose" },
  { text: "chacun", answer: "pronom", level: "medium", tags: ["indéfini"], hint: "remplace une personne" },
  { text: "celui-ci", answer: "pronom", level: "medium", tags: ["démonstratif"], hint: "remplace un nom" },
  { text: "elles", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace un nom" },
  { text: "vous", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace un nom" },
  { text: "moi", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace une personne" },
  { text: "quelqu'un", answer: "pronom", level: "medium", tags: ["indéfini"], hint: "remplace une personne" },
  { text: "lequel", answer: "pronom", level: "hard", tags: ["interrogatif"], hint: "remplace un nom" },
  { text: "je", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace une personne" },
  { text: "tu", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace une personne" },
  { text: "il", answer: "pronom", level: "easy", tags: ["personnel"], hint: "remplace une personne" },
  { text: "laquelle", answer: "pronom", level: "medium", tags: ["relatif"], hint: "remplace un nom" },
  { text: "certains", answer: "pronom", level: "medium", tags: ["indéfini"], hint: "remplace un groupe" },
  { text: "auquel", answer: "pronom", level: "hard", tags: ["relatif"], hint: "remplace un complément" },
  { text: "lesquels", answer: "pronom", level: "hard", tags: ["relatif"], hint: "remplace un groupe" },
  { text: "autrui", answer: "pronom", level: "hard", tags: ["indéfini"], hint: "désigne les autres" },
  { text: "ville", answer: "nom", level: "easy", tags: ["lieu"], hint: "un lieu" },
  { text: "inscription", answer: "nom", level: "medium", tags: ["administration"], hint: "un nom abstrait" },
  { text: "logement", answer: "nom", level: "medium", tags: ["habitation"], hint: "un nom" },
  { text: "formation", answer: "nom", level: "medium", tags: ["études"], hint: "un nom" },
  { text: "rendez-vous", answer: "nom", level: "medium", tags: ["temps"], hint: "un nom composé" },
  { text: "hypothèse", answer: "nom", level: "hard", tags: ["abstraction"], hint: "un nom abstrait" },
  { text: "conséquence", answer: "nom", level: "hard", tags: ["abstraction"], hint: "un nom abstrait" },
  { text: "argument", answer: "nom", level: "hard", tags: ["discours"], hint: "un nom" },
  { text: "phénomène", answer: "nom", level: "hard", tags: ["abstraction"], hint: "un nom" },
  { text: "démarche", answer: "nom", level: "hard", tags: ["méthode"], hint: "un nom" },
  { text: "aller", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "venir", answer: "verbe", level: "easy", tags: ["infinitif"], hint: "une action" },
  { text: "expliquer", answer: "verbe", level: "medium", tags: ["infinitif"], hint: "une action" },
  { text: "réussir", answer: "verbe", level: "medium", tags: ["infinitif"], hint: "une action" },
  { text: "obtenir", answer: "verbe", level: "medium", tags: ["infinitif"], hint: "une action" },
  { text: "analyser", answer: "verbe", level: "hard", tags: ["infinitif"], hint: "une action intellectuelle" },
  { text: "nuancer", answer: "verbe", level: "hard", tags: ["infinitif"], hint: "une action intellectuelle" },
  { text: "supposer", answer: "verbe", level: "hard", tags: ["infinitif"], hint: "une action intellectuelle" },
  { text: "démontrer", answer: "verbe", level: "hard", tags: ["infinitif"], hint: "une action intellectuelle" },
  { text: "petit", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "français", answer: "adjectif", level: "easy", tags: ["nationalité"], hint: "une qualité" },
  { text: "important", answer: "adjectif", level: "easy", tags: ["qualité"], hint: "une qualité" },
  { text: "nécessaire", answer: "adjectif", level: "medium", tags: ["qualité"], hint: "une qualité" },
  { text: "sérieux", answer: "adjectif", level: "medium", tags: ["qualité"], hint: "une qualité" },
  { text: "disponible", answer: "adjectif", level: "medium", tags: ["qualité"], hint: "une qualité" },
  { text: "pertinent", answer: "adjectif", level: "hard", tags: ["argumentation"], hint: "une qualité" },
  { text: "implicite", answer: "adjectif", level: "hard", tags: ["argumentation"], hint: "une qualité" },
  { text: "contradictoire", answer: "adjectif", level: "hard", tags: ["argumentation"], hint: "une qualité" },
  { text: "approximatif", answer: "adjectif", level: "hard", tags: ["argumentation"], hint: "une qualité" },
  { text: "bien", answer: "adverbe", level: "easy", tags: ["manière"], hint: "comment ?" },
  { text: "pourtant", answer: "adverbe", level: "medium", tags: ["opposition"], hint: "nuance la phrase" },
  { text: "clairement", answer: "adverbe", level: "medium", tags: ["manière"], hint: "comment ?" },
  { text: "rarement", answer: "adverbe", level: "medium", tags: ["fréquence"], hint: "combien de fois ?" },
  { text: "néanmoins", answer: "adverbe", level: "hard", tags: ["opposition"], hint: "nuance la phrase" },
  { text: "toutefois", answer: "adverbe", level: "hard", tags: ["opposition"], hint: "nuance la phrase" },
  { text: "explicitement", answer: "adverbe", level: "hard", tags: ["manière"], hint: "comment ?" },
  { text: "progressivement", answer: "adverbe", level: "hard", tags: ["manière"], hint: "comment ?" },
  { text: "le", answer: "determinant", level: "easy", tags: ["défini"], hint: "devant un nom" },
  { text: "la", answer: "determinant", level: "easy", tags: ["défini"], hint: "devant un nom" },
  { text: "les", answer: "determinant", level: "easy", tags: ["défini"], hint: "devant un nom" },
  { text: "un", answer: "determinant", level: "easy", tags: ["indéfini"], hint: "devant un nom" },
  { text: "une", answer: "determinant", level: "easy", tags: ["indéfini"], hint: "devant un nom" },
  { text: "des", answer: "determinant", level: "easy", tags: ["indéfini"], hint: "devant un nom" },
  { text: "à", answer: "preposition", level: "easy", tags: ["lieu"], hint: "introduit un complément" },
  { text: "de", answer: "preposition", level: "easy", tags: ["origine"], hint: "introduit un complément" },
  { text: "dans", answer: "preposition", level: "easy", tags: ["lieu"], hint: "introduit un complément" },
  { text: "sur", answer: "preposition", level: "easy", tags: ["lieu"], hint: "introduit un complément" },
  { text: "avec", answer: "preposition", level: "easy", tags: ["accompagnement"], hint: "introduit un complément" },
  { text: "pendant", answer: "preposition", level: "medium", tags: ["temps"], hint: "introduit un complément" },
  { text: "malgré", answer: "preposition", level: "medium", tags: ["opposition"], hint: "introduit un complément" },
  { text: "depuis", answer: "preposition", level: "medium", tags: ["temps"], hint: "introduit un complément" },
  { text: "entre", answer: "preposition", level: "medium", tags: ["lieu"], hint: "introduit un complément" },
  { text: "selon", answer: "preposition", level: "hard", tags: ["point de vue"], hint: "introduit un complément" },
  { text: "parmi", answer: "preposition", level: "hard", tags: ["ensemble"], hint: "introduit un complément" },
  { text: "hormis", answer: "preposition", level: "hard", tags: ["exclusion"], hint: "introduit un complément" },
  { text: "lors de", answer: "preposition", level: "hard", tags: ["temps"], hint: "introduit un complément" },
  { text: "mais", answer: "conjonction", level: "easy", tags: ["opposition"], hint: "relie deux idées" },
  { text: "et", answer: "conjonction", level: "easy", tags: ["addition"], hint: "relie deux idées" },
  { text: "ou", answer: "conjonction", level: "easy", tags: ["choix"], hint: "relie deux idées" },
  { text: "car", answer: "conjonction", level: "easy", tags: ["cause"], hint: "relie deux idées" },
  { text: "cependant", answer: "conjonction", level: "medium", tags: ["opposition"], hint: "relie deux idées" },
  { text: "quoique", answer: "conjonction", level: "hard", tags: ["concession"], hint: "relie deux idées" },
  { text: "oh", answer: "interjection", level: "easy", tags: ["réaction"], hint: "réaction brève" },
  { text: "ah", answer: "interjection", level: "easy", tags: ["réaction"], hint: "réaction brève" },
  { text: "hélas", answer: "interjection", level: "medium", tags: ["réaction"], hint: "réaction brève" },
  { text: "eh bien", answer: "interjection", level: "medium", tags: ["réaction"], hint: "réaction brève" },
];

const LEXICAL_BUCKETS = {
  alimentation: {
    label: "alimentation",
    color: "#1f9d68",
    hint: "manger, boire, cuisiner",
    errorHint: "mot lié aux repas",
    errorLabel: "champ lexical de l'alimentation",
  },
  transports: {
    label: "transports",
    color: "#2867c8",
    hint: "se déplacer",
    errorHint: "mot lié aux déplacements",
    errorLabel: "champ lexical des transports",
  },
  etudes: {
    label: "études",
    color: "#7557b8",
    hint: "apprendre, lire, passer un examen",
    errorHint: "mot lié à l'école ou l'université",
    errorLabel: "champ lexical des études",
  },
  logement: {
    label: "logement",
    color: "#0f8b8d",
    hint: "pièces, meubles, habitation",
    errorHint: "mot lié à la maison",
    errorLabel: "champ lexical du logement",
  },
  travail: {
    label: "travail",
    color: "#c95f36",
    hint: "emploi, bureau, collègues",
    errorHint: "mot lié à la vie professionnelle",
    errorLabel: "champ lexical du travail",
  },

  meteo_climat: {
    label: "météo / climat",
    color: "#5d7c2f",
    hint: "temps, climat, phénomènes",
    errorHint: "mot lié au temps ou au climat",
    errorLabel: "champ lexical de la météo et du climat",
  },
  sante: {
    label: "santé",
    color: "#1f7a5d",
    hint: "soins, symptômes, prévention",
    errorHint: "mot lié au corps ou aux soins",
    errorLabel: "champ lexical de la santé",
  },
  culture_litterature: {
    label: "culture / littérature",
    color: "#8a5bb8",
    hint: "livres, œuvres, analyse",
    errorHint: "mot lié aux arts, aux textes ou à la culture",
    errorLabel: "champ lexical de la culture et de la littérature",
  },
  administration: {
    label: "administration",
    color: "#8a6d1d",
    hint: "dossier, formulaire, démarches",
    errorHint: "mot lié aux démarches administratives",
    errorLabel: "champ lexical de l'administration",
  },
};

const LEXICAL_ORDER = ["etudes", "logement", "transports", "meteo_climat", "sante", "travail", "culture_litterature", "administration", "alimentation"];

const LEXICAL_ITEMS = [
  { text: "pain", answer: "alimentation", level: "easy", tags: ["aliment"], hint: "à manger" },
  { text: "pomme", answer: "alimentation", level: "easy", tags: ["fruit"], hint: "à manger" },
  { text: "salade", answer: "alimentation", level: "easy", tags: ["aliment"], hint: "à manger" },
  { text: "fourchette", answer: "alimentation", level: "easy", tags: ["ustensile"], hint: "pour manger" },
  { text: "fromage", answer: "alimentation", level: "easy", tags: ["aliment"], hint: "à manger" },
  { text: "eau", answer: "alimentation", level: "easy", tags: ["boisson"], hint: "à boire" },
  { text: "restaurant", answer: "alimentation", level: "medium", tags: ["lieu"], hint: "où l'on mange" },
  { text: "assiette", answer: "alimentation", level: "medium", tags: ["objet"], hint: "pour manger" },
  { text: "casserole", answer: "alimentation", level: "medium", tags: ["objet"], hint: "pour cuisiner" },
  { text: "recette", answer: "alimentation", level: "hard", tags: ["cuisine"], hint: "pour préparer un plat" },
  { text: "bus", answer: "transports", level: "easy", tags: ["véhicule"], hint: "pour se déplacer" },
  { text: "gare", answer: "transports", level: "easy", tags: ["lieu"], hint: "lieu de départ" },
  { text: "train", answer: "transports", level: "easy", tags: ["véhicule"], hint: "pour voyager" },
  { text: "vélo", answer: "transports", level: "easy", tags: ["véhicule"], hint: "pour se déplacer" },
  { text: "métro", answer: "transports", level: "easy", tags: ["véhicule"], hint: "en ville" },
  { text: "billet", answer: "transports", level: "medium", tags: ["document"], hint: "pour voyager" },
  { text: "aéroport", answer: "transports", level: "medium", tags: ["lieu"], hint: "pour prendre l'avion" },
  { text: "tramway", answer: "transports", level: "medium", tags: ["véhicule"], hint: "transport urbain" },
  { text: "parking", answer: "transports", level: "medium", tags: ["lieu"], hint: "pour garer une voiture" },
  { text: "passager", answer: "transports", level: "hard", tags: ["personne"], hint: "personne qui voyage" },
  { text: "professeur", answer: "etudes", level: "easy", tags: ["personne"], hint: "à l'école" },
  { text: "cahier", answer: "etudes", level: "easy", tags: ["objet"], hint: "pour écrire" },
  { text: "examen", answer: "etudes", level: "easy", tags: ["évaluation"], hint: "à réussir" },
  { text: "bibliothèque", answer: "etudes", level: "easy", tags: ["lieu"], hint: "pour lire ou étudier" },
  { text: "leçon", answer: "etudes", level: "easy", tags: ["cours"], hint: "à apprendre" },
  { text: "diplôme", answer: "etudes", level: "medium", tags: ["document"], hint: "après des études" },
  { text: "classe", answer: "etudes", level: "medium", tags: ["lieu"], hint: "lieu d'apprentissage" },
  { text: "devoir", answer: "etudes", level: "medium", tags: ["activité"], hint: "à faire pour apprendre" },
  { text: "université", answer: "etudes", level: "medium", tags: ["lieu"], hint: "après le lycée" },
  { text: "manuel", answer: "etudes", level: "hard", tags: ["objet"], hint: "livre de cours" },
  { text: "chambre", answer: "logement", level: "easy", tags: ["pièce"], hint: "dans une maison" },
  { text: "clé", answer: "logement", level: "easy", tags: ["objet"], hint: "pour ouvrir" },
  { text: "canapé", answer: "logement", level: "easy", tags: ["meuble"], hint: "dans le salon" },
  { text: "loyer", answer: "logement", level: "medium", tags: ["argent"], hint: "à payer chaque mois" },
  { text: "douche", answer: "logement", level: "medium", tags: ["pièce"], hint: "dans la salle de bain" },
  { text: "balcon", answer: "logement", level: "medium", tags: ["espace"], hint: "à l'extérieur du logement" },
  { text: "placard", answer: "logement", level: "medium", tags: ["meuble"], hint: "pour ranger" },
  { text: "immeuble", answer: "logement", level: "hard", tags: ["bâtiment"], hint: "plusieurs appartements" },
  { text: "entretien", answer: "travail", level: "easy", tags: ["recrutement"], hint: "avant un emploi" },
  { text: "bureau", answer: "travail", level: "easy", tags: ["lieu"], hint: "où l'on travaille" },
  { text: "salaire", answer: "travail", level: "easy", tags: ["argent"], hint: "argent du travail" },
  { text: "collègue", answer: "travail", level: "easy", tags: ["personne"], hint: "personne au travail" },
  { text: "réunion", answer: "travail", level: "medium", tags: ["activité"], hint: "moment professionnel" },
  { text: "contrat", answer: "travail", level: "medium", tags: ["document"], hint: "document d'emploi" },
  { text: "poste", answer: "travail", level: "medium", tags: ["emploi"], hint: "emploi occupé" },
  { text: "entreprise", answer: "travail", level: "medium", tags: ["lieu"], hint: "lieu professionnel" },

  { text: "cours", answer: "etudes", level: "easy", tags: ["université"], hint: "à suivre" },
  { text: "étudiant", answer: "etudes", level: "easy", tags: ["personne"], hint: "à l'université" },
  { text: "emploi du temps", answer: "etudes", level: "medium", tags: ["organisation"], hint: "planning des cours" },
  { text: "absence", answer: "etudes", level: "medium", tags: ["administration"], hint: "non-présence" },
  { text: "méthodologie", answer: "etudes", level: "hard", tags: ["université"], hint: "façon de travailler" },
  { text: "problématique", answer: "etudes", level: "hard", tags: ["université"], hint: "question centrale" },
  { text: "synthèse", answer: "etudes", level: "hard", tags: ["université"], hint: "résumé organisé" },
  { text: "corpus", answer: "etudes", level: "hard", tags: ["université"], hint: "ensemble de documents" },
  { text: "commentaire", answer: "etudes", level: "hard", tags: ["université"], hint: "analyse écrite" },
  { text: "lit", answer: "logement", level: "easy", tags: ["meuble"], hint: "dans une chambre" },
  { text: "cuisine", answer: "logement", level: "easy", tags: ["pièce"], hint: "pièce du logement" },
  { text: "caution", answer: "logement", level: "medium", tags: ["argent"], hint: "garantie versée" },
  { text: "propriétaire", answer: "logement", level: "medium", tags: ["personne"], hint: "possède le logement" },
  { text: "colocataire", answer: "logement", level: "medium", tags: ["personne"], hint: "partage le logement" },
  { text: "précarité", answer: "logement", level: "hard", tags: ["abstrait"], hint: "situation instable" },
  { text: "hébergement", answer: "logement", level: "hard", tags: ["habitation"], hint: "solution pour se loger" },
  { text: "charges", answer: "logement", level: "hard", tags: ["argent"], hint: "frais liés au logement" },
  { text: "bail", answer: "logement", level: "hard", tags: ["document"], hint: "contrat de location" },
  { text: "garantie", answer: "logement", level: "hard", tags: ["argent"], hint: "sécurité financière" },
  { text: "rue", answer: "transports", level: "easy", tags: ["ville"], hint: "dans la ville" },
  { text: "place", answer: "transports", level: "easy", tags: ["ville"], hint: "espace urbain" },
  { text: "correspondance", answer: "transports", level: "medium", tags: ["trajet"], hint: "changement de ligne" },
  { text: "arrêt", answer: "transports", level: "medium", tags: ["ville"], hint: "lieu d'attente" },
  { text: "abonnement", answer: "transports", level: "medium", tags: ["document"], hint: "titre régulier" },
  { text: "trajet", answer: "transports", level: "medium", tags: ["déplacement"], hint: "chemin parcouru" },
  { text: "mobilité", answer: "transports", level: "hard", tags: ["ville"], hint: "capacité à se déplacer" },
  { text: "accessibilité", answer: "transports", level: "hard", tags: ["ville"], hint: "facilité d'accès" },
  { text: "agglomération", answer: "transports", level: "hard", tags: ["ville"], hint: "ensemble urbain" },
  { text: "pluie", answer: "meteo_climat", level: "easy", tags: ["météo"], hint: "temps humide" },
  { text: "soleil", answer: "meteo_climat", level: "easy", tags: ["météo"], hint: "temps clair" },
  { text: "froid", answer: "meteo_climat", level: "easy", tags: ["température"], hint: "basse température" },
  { text: "chaud", answer: "meteo_climat", level: "easy", tags: ["température"], hint: "haute température" },
  { text: "orage", answer: "meteo_climat", level: "medium", tags: ["météo"], hint: "pluie et tonnerre" },
  { text: "nuageux", answer: "meteo_climat", level: "medium", tags: ["météo"], hint: "avec des nuages" },
  { text: "température", answer: "meteo_climat", level: "medium", tags: ["météo"], hint: "degré de chaleur" },
  { text: "bulletin", answer: "meteo_climat", level: "medium", tags: ["information"], hint: "annonce météo" },
  { text: "sécheresse", answer: "meteo_climat", level: "hard", tags: ["climat"], hint: "manque d'eau" },
  { text: "canicule", answer: "meteo_climat", level: "hard", tags: ["climat"], hint: "forte chaleur" },
  { text: "perturbation", answer: "meteo_climat", level: "hard", tags: ["météo"], hint: "changement du temps" },
  { text: "vigilance", answer: "meteo_climat", level: "hard", tags: ["alerte"], hint: "alerte météo" },
  { text: "médecin", answer: "sante", level: "easy", tags: ["personne"], hint: "soigne" },
  { text: "pharmacie", answer: "sante", level: "easy", tags: ["lieu"], hint: "achète des médicaments" },
  { text: "malade", answer: "sante", level: "easy", tags: ["état"], hint: "pas en bonne santé" },
  { text: "ordonnance", answer: "sante", level: "medium", tags: ["document"], hint: "prescription médicale" },
  { text: "rendez-vous", answer: "sante", level: "medium", tags: ["consultation"], hint: "moment prévu" },
  { text: "symptôme", answer: "sante", level: "medium", tags: ["signe"], hint: "signe d'une maladie" },
  { text: "prévention", answer: "sante", level: "hard", tags: ["santé publique"], hint: "éviter un problème" },
  { text: "diagnostic", answer: "sante", level: "hard", tags: ["médecine"], hint: "identification d'une maladie" },
  { text: "traitement", answer: "sante", level: "hard", tags: ["médecine"], hint: "soin proposé" },
  { text: "suivi", answer: "sante", level: "hard", tags: ["médecine"], hint: "contrôle dans la durée" },
  { text: "œuvre", answer: "culture_litterature", level: "medium", tags: ["culture"], hint: "création artistique" },
  { text: "roman", answer: "culture_litterature", level: "medium", tags: ["littérature"], hint: "genre narratif" },
  { text: "auteur", answer: "culture_litterature", level: "medium", tags: ["littérature"], hint: "écrit un texte" },
  { text: "genre", answer: "culture_litterature", level: "hard", tags: ["analyse"], hint: "catégorie artistique" },
  { text: "registre", answer: "culture_litterature", level: "hard", tags: ["analyse"], hint: "ton d'un texte" },
  { text: "narrateur", answer: "culture_litterature", level: "hard", tags: ["analyse"], hint: "voix du récit" },
  { text: "dossier", answer: "administration", level: "medium", tags: ["document"], hint: "ensemble de pièces" },
  { text: "formulaire", answer: "administration", level: "medium", tags: ["document"], hint: "document à remplir" },
  { text: "attestation", answer: "administration", level: "medium", tags: ["document"], hint: "preuve écrite" },
  { text: "démarche", answer: "administration", level: "hard", tags: ["procédure"], hint: "procédure à suivre" },
  { text: "récépissé", answer: "administration", level: "hard", tags: ["document"], hint: "preuve de dépôt" },
  { text: "guichet", answer: "administration", level: "hard", tags: ["lieu"], hint: "point d'accueil" },
];

const TOOL_BUCKETS = {
  cause: {
    label: "cause",
    color: "#0f8b8d",
    hint: "explique pourquoi",
    errorHint: "introduit une raison",
    errorLabel: "mot outil de cause",
  },
  consequence: {
    label: "conséquence",
    color: "#2867c8",
    hint: "indique le résultat",
    errorHint: "annonce un effet ou un résultat",
    errorLabel: "mot outil de conséquence",
  },
  opposition: {
    label: "opposition",
    color: "#c95f36",
    hint: "oppose deux idées",
    errorHint: "marque un contraste",
    errorLabel: "mot outil d'opposition",
  },
  concession: {
    label: "concession",
    color: "#8a5bb8",
    hint: "admet une limite",
    errorHint: "nuance malgré un obstacle",
    errorLabel: "mot outil de concession",
  },
  addition: {
    label: "addition",
    color: "#1f9d68",
    hint: "ajoute une idée",
    errorHint: "sert à ajouter une information",
    errorLabel: "mot outil d'addition",
  },
  but: {
    label: "but",
    color: "#8a6d1d",
    hint: "exprime l'objectif",
    errorHint: "introduit un objectif",
    errorLabel: "mot outil de but",
  },
  condition: {
    label: "condition",
    color: "#5d7c2f",
    hint: "pose une condition",
    errorHint: "introduit une hypothèse ou une condition",
    errorLabel: "mot outil de condition",
  },
  temps: {
    label: "temps",
    color: "#a64f77",
    hint: "situe dans le temps",
    errorHint: "indique quand ou pendant quelle durée",
    errorLabel: "mot outil de temps",
  },
  reformulation: {
    label: "reformulation",
    color: "#6b7280",
    hint: "dit autrement",
    errorHint: "sert à reformuler",
    errorLabel: "mot outil de reformulation",
  },
  exemple: {
    label: "exemple",
    color: "#8d4f20",
    hint: "introduit un exemple",
    errorHint: "annonce une illustration",
    errorLabel: "mot outil d'exemple",
  },
};

const TOOL_ORDER = ["cause", "consequence", "opposition", "addition", "but", "condition", "temps", "concession", "reformulation", "exemple"];

const TOOL_ITEMS = [
  { text: "parce que", answer: "cause", level: "easy", tags: ["raison"], hint: "pourquoi ?" },
  { text: "car", answer: "cause", level: "easy", tags: ["raison"], hint: "raison" },
  { text: "puisque", answer: "cause", level: "medium", tags: ["raison"], hint: "raison connue" },
  { text: "étant donné que", answer: "cause", level: "hard", tags: ["raison"], hint: "raison posée au départ" },
  { text: "donc", answer: "consequence", level: "easy", tags: ["résultat"], hint: "résultat" },
  { text: "c'est pourquoi", answer: "consequence", level: "easy", tags: ["résultat"], hint: "résultat" },
  { text: "alors", answer: "consequence", level: "medium", tags: ["résultat"], hint: "résultat" },
  { text: "par conséquent", answer: "consequence", level: "hard", tags: ["résultat"], hint: "résultat formel" },
  { text: "mais", answer: "opposition", level: "easy", tags: ["contraste"], hint: "contraste" },
  { text: "au contraire", answer: "opposition", level: "easy", tags: ["contraste"], hint: "contraste" },
  { text: "pourtant", answer: "opposition", level: "medium", tags: ["contraste"], hint: "contraste inattendu" },
  { text: "cependant", answer: "opposition", level: "medium", tags: ["contraste"], hint: "contraste" },
  { text: "néanmoins", answer: "opposition", level: "hard", tags: ["contraste"], hint: "contraste formel" },
  { text: "toutefois", answer: "concession", level: "hard", tags: ["nuance"], hint: "limite l'idée" },
  { text: "et", answer: "addition", level: "easy", tags: ["ajout"], hint: "ajoute" },
  { text: "en plus", answer: "addition", level: "medium", tags: ["ajout"], hint: "ajoute" },
  { text: "de surcroît", answer: "addition", level: "hard", tags: ["ajout"], hint: "ajout formel" },
  { text: "pour", answer: "but", level: "easy", tags: ["objectif"], hint: "objectif" },
  { text: "afin de", answer: "but", level: "medium", tags: ["objectif"], hint: "objectif" },
  { text: "afin que", answer: "but", level: "hard", tags: ["objectif"], hint: "objectif avec verbe conjugué" },
  { text: "si", answer: "condition", level: "easy", tags: ["hypothèse"], hint: "condition" },
  { text: "à condition de", answer: "condition", level: "medium", tags: ["condition"], hint: "condition avec infinitif" },
  { text: "à condition que", answer: "condition", level: "hard", tags: ["condition"], hint: "condition avec verbe conjugué" },
  { text: "quand", answer: "temps", level: "easy", tags: ["moment"], hint: "moment" },
  { text: "pendant que", answer: "temps", level: "medium", tags: ["simultanéité"], hint: "en même temps" },
  { text: "tandis que", answer: "temps", level: "hard", tags: ["simultanéité"], hint: "en même temps" },
  { text: "c'est-à-dire", answer: "reformulation", level: "medium", tags: ["explication"], hint: "dit autrement" },
  { text: "autrement dit", answer: "reformulation", level: "hard", tags: ["explication"], hint: "dit autrement" },
  { text: "par exemple", answer: "exemple", level: "easy", tags: ["illustration"], hint: "exemple" },
  { text: "à titre d'exemple", answer: "exemple", level: "hard", tags: ["illustration"], hint: "exemple formel" },
];

const GAME_MODES = {
  tenses: {
    id: "tenses",
    label: "Temps verbaux",
    description: "Classe les formes conjuguées par temps, du présent fréquent au passé simple littéraire.",
    headerEyebrow: "Classement des temps",
    headerTitle: "Quelle boîte choisir ?",
    itemLabel: "forme verbale",
    helpTitle: "Rappel des terminaisons",
    buckets: TENSES,
    bucketOrder: TENSE_ORDER,
    initialBuckets: INITIAL_TENSES,
    items: GAME_FORMS,
    testItems: TEST_FORMS,
    unlocks: {
      A2: { futur: 10 },
      B1: { futur: 7, conditionnel_present: 16 },
      B2: { futur: 5, conditionnel_present: 10, passe_simple: 18 },
    },
    bestLabel: "Temps le plus réussi",
    hardestLabel: "Temps à retravailler",
    emptyBestLabel: "à découvrir",
    noProblemLabel: "aucun",
    weightIrregulars: true,
  },
  grammar: {
    id: "grammar",
    label: "Catégories grammaticales",
    description: "Trie les mots par nature grammaticale, des catégories fréquentes aux formes plus fines.",
    headerEyebrow: "Catégories grammaticales",
    headerTitle: "Quelle nature grammaticale ?",
    itemLabel: "mot",
    helpTitle: "Mini-repères grammaticaux",
    buckets: GRAMMAR_BUCKETS,
    bucketOrder: GRAMMAR_ORDER,
    initialBuckets: GRAMMAR_ORDER.slice(0, 3),
    items: GRAMMAR_ITEMS,
    unlocks: {
      A2: { adverbe: 8, pronom: 16, determinant: 22 },
      B1: { adverbe: 6, pronom: 12, determinant: 18, preposition: 24, conjonction: 28 },
      B2: { adverbe: 5, pronom: 10, determinant: 14, preposition: 18, conjonction: 22, interjection: 26 },
    },
    bestLabel: "Catégorie la plus réussie",
    hardestLabel: "Catégorie à retravailler",
    emptyBestLabel: "à découvrir",
    noProblemLabel: "aucune",
  },
  lexical: {
    id: "lexical",
    label: "Champs lexicaux",
    description: "Classe le lexique par champs utiles aux études, à la vie quotidienne et au FOU.",
    headerEyebrow: "Champs lexicaux",
    headerTitle: "Dans quelle famille va ce mot ?",
    itemLabel: "mot",
    helpTitle: "Familles de vocabulaire",
    buckets: LEXICAL_BUCKETS,
    bucketOrder: LEXICAL_ORDER,
    initialBuckets: LEXICAL_ORDER.slice(0, 3),
    items: LEXICAL_ITEMS,
    unlocks: {
      A2: { meteo_climat: 8, sante: 16, travail: 24 },
      B1: { meteo_climat: 6, sante: 12, travail: 18, administration: 24 },
      B2: { meteo_climat: 5, sante: 10, travail: 15, culture_litterature: 20, administration: 24, alimentation: 28 },
    },
    bestLabel: "Champ le plus réussi",
    hardestLabel: "Champ à retravailler",
    emptyBestLabel: "à découvrir",
    noProblemLabel: "aucun",
  },
  tools: {
    id: "tools",
    label: "Mots outils",
    description: "Trie les mots outils selon leur rôle logique : cause, opposition, but, exemple...",
    headerEyebrow: "Mots outils",
    headerTitle: "Quelle famille de mot outil ?",
    itemLabel: "mot outil",
    helpTitle: "Rôle des mots outils",
    buckets: TOOL_BUCKETS,
    bucketOrder: TOOL_ORDER,
    initialBuckets: TOOL_ORDER.slice(0, 3),
    items: TOOL_ITEMS,
    unlocks: {
      A2: { addition: 8, but: 14, condition: 20, temps: 24, exemple: 28 },
      B1: { addition: 6, but: 10, condition: 14, temps: 18, concession: 22, reformulation: 26, exemple: 28 },
      B2: { addition: 5, but: 9, condition: 13, temps: 17, concession: 20, reformulation: 23, exemple: 26 },
    },
    bestLabel: "Famille la plus réussie",
    hardestLabel: "Famille à retravailler",
    emptyBestLabel: "à découvrir",
    noProblemLabel: "aucune",
  },
};
